"""empty message

Revision ID: 04b64907e4b6
Revises: 
Create Date: 2018-01-22 16:45:31.231881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b64907e4b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('vs_category', sa.String(length=128), nullable=False),
    sa.Column('vs_other_c', sa.String(length=128), nullable=True),
    sa.Column('vs', sa.String(length=128), nullable=False),
    sa.Column('al', sa.String(length=128), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vs_push', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('image_name', sa.String(length=128), nullable=True),
    sa.Column('image_path', sa.String(length=256), nullable=True),
    sa.Column('cea_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gambler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('register_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_gambler_id'), 'gambler', ['id'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vs_type', sa.String(length=128), nullable=False),
    sa.Column('vs', sa.String(length=128), nullable=False),
    sa.Column('vs_code', sa.String(length=128), nullable=False),
    sa.Column('vs_time', sa.String(length=128), nullable=False),
    sa.Column('victory', sa.String(length=128), nullable=False),
    sa.Column('ping', sa.String(length=128), nullable=False),
    sa.Column('fail', sa.String(length=128), nullable=False),
    sa.Column('victory_code', sa.String(length=128), nullable=False),
    sa.Column('ping_code', sa.String(length=128), nullable=False),
    sa.Column('fail_code', sa.String(length=128), nullable=False),
    sa.Column('let_ball', sa.String(length=128), nullable=False),
    sa.Column('cea_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=64), nullable=True),
    sa.Column('login_t', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('logout_t', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('register_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('price', sa.String(length=64), nullable=False),
    sa.Column('area', sa.String(length=64), nullable=True),
    sa.Column('households', sa.String(length=64), nullable=False),
    sa.Column('describe', sa.String(length=1024), nullable=True),
    sa.Column('image_name', sa.String(length=128), nullable=True),
    sa.Column('image_path', sa.String(length=256), nullable=True),
    sa.Column('auth_id', sa.Integer(), nullable=True),
    sa.Column('release_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('monitor')
    op.drop_table('match')
    op.drop_index(op.f('ix_gambler_id'), table_name='gambler')
    op.drop_table('gambler')
    op.drop_table('article')
    # ### end Alembic commands ###
