"""empty message

Revision ID: cb55a30fe001
Revises: 20470654da08
Create Date: 2018-01-24 11:31:09.719337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb55a30fe001'
down_revision = '20470654da08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push', sa.Column('main_push', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push', 'main_push')
    # ### end Alembic commands ###
