"""empty message

Revision ID: d3840957b60c
Revises: 57a1c8753851
Create Date: 2018-01-29 14:25:49.492880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3840957b60c'
down_revision = '57a1c8753851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nkname', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=64), nullable=True),
    sa.Column('u_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_id'], ['gambler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('niub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niub',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vs', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('victory', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('ping', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('fail', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('victory_code', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('ping_code', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('fail_code', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('let_ball', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('pusher', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('main_push', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=False),
    sa.Column('cost', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('describe', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('cea_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('profile')
    # ### end Alembic commands ###
