"""empty message

Revision ID: 5a5ebd34bbe1
Revises: 93c2f22e482b
Create Date: 2018-04-09 10:29:29.793192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5ebd34bbe1'
down_revision = '93c2f22e482b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IpList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=128), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('area', sa.String(length=64), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('describe', sa.String(length=1024), nullable=True),
    sa.Column('release_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IpList')
    # ### end Alembic commands ###
