"""empty message

Revision ID: 7971a349df35
Revises: 5a5ebd34bbe1
Create Date: 2018-04-27 10:03:53.977933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7971a349df35'
down_revision = '5a5ebd34bbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biao1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jy', sa.String(length=1024), nullable=True),
    sa.Column('num', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biao2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jy', sa.String(length=1024), nullable=True),
    sa.Column('num', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test2')
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8_bin', length=80), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation='utf8_bin', length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', 'author'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('test2',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8_bin', length=80), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation='utf8_bin', length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('biao2')
    op.drop_table('biao1')
    # ### end Alembic commands ###
