"""empty message

Revision ID: 93c2f22e482b
Revises: b80a2d8e0d10
Create Date: 2018-01-18 14:24:37.164526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93c2f22e482b'
down_revision = 'b80a2d8e0d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('vs_category', sa.String(length=128), nullable=False),
    sa.Column('vs_other_c', sa.String(length=128), nullable=True),
    sa.Column('vs', sa.String(length=128), nullable=False),
    sa.Column('al', sa.String(length=128), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(length=128), nullable=False),
    sa.Column('vs_push', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('image_name', sa.String(length=128), nullable=True),
    sa.Column('image_path', sa.String(length=256), nullable=True),
    sa.Column('cea_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gambler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('register_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_gambler_id'), 'gambler', ['id'], unique=False)
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.Integer(), nullable=True),
    sa.Column('login_t', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('logout_t', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('logtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logtime',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('mobile', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('login_t', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('logout_t', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('monitor')
    op.drop_index(op.f('ix_gambler_id'), table_name='gambler')
    op.drop_table('gambler')
    op.drop_table('article')
    # ### end Alembic commands ###
