"""empty message

Revision ID: b80a2d8e0d10
Revises: a2dbab896141
Create Date: 2018-01-17 09:21:23.536050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80a2d8e0d10'
down_revision = 'a2dbab896141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.Integer(), nullable=True),
    sa.Column('login_t', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('logout_t', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vs_type', sa.String(length=128), nullable=False),
    sa.Column('vs', sa.String(length=128), nullable=False),
    sa.Column('vs_code', sa.String(length=128), nullable=False),
    sa.Column('vs_time', sa.String(length=128), nullable=False),
    sa.Column('victory', sa.String(length=128), nullable=False),
    sa.Column('ping', sa.String(length=128), nullable=False),
    sa.Column('fail', sa.String(length=128), nullable=False),
    sa.Column('victory_code', sa.String(length=128), nullable=False),
    sa.Column('ping_code', sa.String(length=128), nullable=False),
    sa.Column('fail_code', sa.String(length=128), nullable=False),
    sa.Column('let_ball', sa.String(length=128), nullable=False),
    sa.Column('cea_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('logtime')
    # ### end Alembic commands ###
