"""empty message

Revision ID: fd59f7900a67
Revises: 
Create Date: 2018-10-29 16:44:49.156484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd59f7900a67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gambler',
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('create_timestamp', sa.String(length=128), nullable=True),
    sa.Column('update_time', sa.String(length=128), server_default='', nullable=True),
    sa.Column('update_timestamp', sa.String(length=128), server_default='', nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tel', sa.String(length=64), nullable=False),
    sa.Column('_password', sa.String(length=256), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('register_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('join_time', sa.String(length=128), server_default='', nullable=True),
    sa.Column('logout_time', sa.String(length=128), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tel')
    )
    op.create_index(op.f('ix_gambler_id'), 'gambler', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gambler_id'), table_name='gambler')
    op.drop_table('gambler')
    # ### end Alembic commands ###
